services:
  website:
    build:
      context: .
      dockerfile: ./Dockerfile
    ulimits: # needed to get around some weird docker issues
      nofile:
        soft: 1024
        hard: 1024
    # workaround until i can figure out why the server keeps randomly crashing
    restart: always
    environment:
      WISP_SECRET_KEY: ${WISP_SECRET_KEY?ERROR}
