services:
  website:
    build:
      context: .
      dockerfile: ./Dockerfile
    ulimits: # needed to get around some weird docker issues
      nofile:
        soft: 1024
        hard: 1024
    restart: unless-stopped
    environment:
      WISP_SECRET_KEY: ${WISP_SECRET_KEY?ERROR}
